### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by LU1371046** [k8spacket/k8spacket#15] opened 2022-12-09 09:02 UTC
There is a problem with the test in the grafana data source, and the panel has no data
![image](https://user-images.githubusercontent.com/23622230/206663977-fdfb25ee-bb72-440e-b394-a3202c375d91.png)
![image](https://user-images.githubusercontent.com/23622230/206664031-217899f3-f229-445f-b80d-8ede784b98b7.png)
How to check availability after deploying k8spacket？
![image](https://user-images.githubusercontent.com/23622230/206664269-e54fcbb4-678b-4883-a5f6-0c68a9c9cdd1.png)
Check that the metrics are available. It is normal for curl 10.64.41.146:8080/nodegraph to output 404 page not found. If it is normal, is there any configuration requirement for grafana? It cannot be displayed after online deployment

**Comment by k8spacket** [comment] 2022-12-09 10:37
@LU1371046 

You need to build a path according to used plugin requirements (see API Configuration fields and data on https://grafana.com/grafana/plugins/hamedkarbasi93-nodegraphapi-datasource/ )

result:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/95187481/206683308-43fe1491-f6ba-464b-a44a-93833051d377.png">

**Comment by k8spacket** [comment] 2022-12-19 08:30
@LU1371046 
This thread is inactive for 10 days.

I'm going to close this issue. If you will have more questions, feel free to reopen this or a new issue

**Comment by zhutong196** [comment] 2023-01-12 02:01
I have same question? How to resolve this question?
<img width="939" alt="image" src="https://user-images.githubusercontent.com/48009847/211957890-7838cebe-dfe5-4b3f-8837-7518650955b3.png">
metrics is normal 
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/48009847/211957986-f5930988-9188-4f18-9055-749b946d87be.png">

**Comment by LU1371046** [comment] 2023-01-12 08:30
这个不支持在虚拟机上使用

**Comment by LU1371046** [comment] 2023-01-12 08:30
> 我有同样的问题？如何解决这个问题？ 指标正常 <img alt="图片" width="939" src="https://user-images.githubusercontent.com/48009847/211957890-7838cebe-dfe5-4b3f-8837-7518650955b3.png"> <img alt="图片" width="1007" src="https://user-images.githubusercontent.com/48009847/211957986-f5930988-9188-4f18-9055-749b946d87be.png">

不要用虚拟机

**Comment by k8spacket** [comment] 2023-01-12 08:31
Hi @zhutong196 
It looks like k8spacket didn't start any plugins on startup.

Could you share the logs from the k8spacket workload? There should be information about loaded plugins:
```
k -n k8spacket logs <k8spacket-pod-name> -f -c k8spacket                                                                                                                                                                                                         

plugins/nodegraph-x86_64.so
plugins/tls-parser-x86_64.so
2023/01/12 08:26:14 Serving requests on port 6676
2023/01/12 08:26:14 Refreshing interfaces for capturing...
Getting k8s resources
2023/01/12 08:26:15 Starting capture on interface "azv98340604ff0"
2023/01/12 08:26:15 Starting capture on interface "azv46a1bc8c07a"
2023/01/12 08:26:15 Starting capture on interface "azvb3a4e067125"
2023/01/12 08:26:15 Starting capture on interface "azvf7f07f45cd7"
2023/01/12 08:26:15 reading in packets
```

Additionally, you can check logs in the init container with the command:
```
k -n k8spacket logs <k8spacket-pod-name> -f -c init-k8spacket                                                                                                                                                                                              

Connecting to github.com (140.82.121.4:443)
wget: note: TLS certificate validation not implemented
Connecting to objects.githubusercontent.com (185.199.109.133:443)
saving to 'nodegraph-x86_64.so'
nodegraph-x86_64.so   23% |*******                         | 14.1M  0:00:03 ETA
nodegraph-x86_64.so   51% |****************                | 31.0M  0:00:01 ETA
nodegraph-x86_64.so   76% |************************        | 45.7M  0:00:00 ETA
nodegraph-x86_64.so  100% |********************************| 59.9M  0:00:00 ETA
'nodegraph-x86_64.so' saved
Connecting to github.com (140.82.121.3:443)
Connecting to objects.githubusercontent.com (185.199.108.133:443)
saving to 'tls-parser-x86_64.so'
tls-parser-x86_64.so   0% |                                |  127k  0:08:04 ETA
tls-parser-x86_64.so   8% |**                              | 5408k  0:00:20 ETA
tls-parser-x86_64.so  33% |**********                      | 20.0M  0:00:06 ETA
tls-parser-x86_64.so  59% |*******************             | 36.0M  0:00:02 ETA
tls-parser-x86_64.so  86% |***************************     | 52.0M  0:00:00 ETA
tls-parser-x86_64.so 100% |********************************| 60.3M  0:00:00 ETA
'tls-parser-x86_64.so' saved
```

**Comment by zhutong196** [comment] 2023-01-13 01:52
> Hi @zhutong196 It looks like k8spacket didn't start any plugins on startup.
> 
> Could you share the logs from the k8spacket workload? There should be information about loaded plugins:
> 
> ```
> k -n k8spacket logs <k8spacket-pod-name> -f -c k8spacket                                                                                                                                                                                                         
> 
> plugins/nodegraph-x86_64.so
> plugins/tls-parser-x86_64.so
> 2023/01/12 08:26:14 Serving requests on port 6676
> 2023/01/12 08:26:14 Refreshing interfaces for capturing...
> Getting k8s resources
> 2023/01/12 08:26:15 Starting capture on interface "azv98340604ff0"
> 2023/01/12 08:26:15 Starting capture on interface "azv46a1bc8c07a"
> 2023/01/12 08:26:15 Starting capture on interface "azvb3a4e067125"
> 2023/01/12 08:26:15 Starting capture on interface "azvf7f07f45cd7"
> 2023/01/12 08:26:15 reading in packets
> ```
> 
> Additionally, you can check logs in the init container with the command:
> 
> ```
> k -n k8spacket logs <k8spacket-pod-name> -f -c init-k8spacket                                                                                                                                                                                              
> 
> Connecting to github.com (140.82.121.4:443)
> wget: note: TLS certificate validation not implemented
> Connecting to objects.githubusercontent.com (185.199.109.133:443)
> saving to 'nodegraph-x86_64.so'
> nodegraph-x86_64.so   23% |*******                         | 14.1M  0:00:03 ETA
> nodegraph-x86_64.so   51% |****************                | 31.0M  0:00:01 ETA
> nodegraph-x86_64.so   76% |************************        | 45.7M  0:00:00 ETA
> nodegraph-x86_64.so  100% |********************************| 59.9M  0:00:00 ETA
> 'nodegraph-x86_64.so' saved
> Connecting to github.com (140.82.121.3:443)
> Connecting to objects.githubusercontent.com (185.199.108.133:443)
> saving to 'tls-parser-x86_64.so'
> tls-parser-x86_64.so   0% |                                |  127k  0:08:04 ETA
> tls-parser-x86_64.so   8% |**                              | 5408k  0:00:20 ETA
> tls-parser-x86_64.so  33% |**********                      | 20.0M  0:00:06 ETA
> tls-parser-x86_64.so  59% |*******************             | 36.0M  0:00:02 ETA
> tls-parser-x86_64.so  86% |***************************     | 52.0M  0:00:00 ETA
> tls-parser-x86_64.so 100% |********************************| 60.3M  0:00:00 ETA
> 'tls-parser-x86_64.so' saved
> ```
Download plugin failed，Can I install plugin offline? 
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/48009847/212218660-d063e0d2-b288-499a-8e68-38213fe7ee69.png">

**Comment by k8spacket** [comment] 2023-01-13 12:32
Hi @zhutong196 

I see the problem is with resolving the `eval` command when an `init-container` downloads plugins. See https://github.com/k8spacket/k8spacket-helm-chart/blob/master/charts/k8spacket/templates/daemonset.yaml#L49

To download them without resolving machine architecture create simple `custom-values.yaml` file with the content:
```
k8sPacket:
  plugins:
    - https://github.com/k8spacket/plugins/releases/download/v1.0.1/nodegraph-{{arch}}.so
    - https://github.com/k8spacket/plugins/releases/download/v1.0.1/tls-parser-{{arch}}.so
```
where `{{arch}}` is the architecture of your k8s cluster nodes (`x86_64` and `aarch64` available currently, see on the releases page: https://github.com/k8spacket/plugins/releases)

and upgrade k8spacket with the command:
```
helm upgrade --install k8spacket --namespace k8spacket k8spacket/k8spacket -f custom-values.yaml
```

Additionally, there is a new version 1.1.0 of k8spacket and plugins available. 

I supposed the `arch` command is available everywhere, but maybe it was the wrong assumption. I'll fix it.

**Comment by k8spacket** [comment] 2023-01-14 09:49
@zhutong196 
What kind of architecture and the operating system does your K8S node use?

**Comment by k8spacket** [comment] 2023-01-25 08:52
@zhutong196 
This thread is inactive for more than 10 days.

I'm going to close this issue.

**Closed by k8spacket** 2023-01-25 08:52 UTC
