### ISSUE TITLE
Metrics exists from old deleted pods.

### ISSUE THREAD

**Issue by gevorgkhachatryan** [k8spacket/k8spacket#45] opened 2024-02-29 14:59 UTC
I encountered an issue following an installation. Upon reviewing the graph, I observed that metrics from previously deleted pods are still present. These metrics persist with the same fixed value recorded at the time of the pod's deletion. Could you please adjust the system so these old pods no longer transmit data, while ensuring their historical data remains accessible? Because if I will deploy this on the production cluster it will kill the Prometheus server after a few seconds. This also breaks the accuracy of the data and dashboard. Thank you.

**Comment by k8spacket** [comment] 2024-03-03 15:12
Hi @gevorgkhachatryan 
Let me understand better the problem.

As far as I understand by the sentence `previously deleted pods` do you mean all other pods than k8spacket pods?

1. If the problem is connected with dashboard `k8spacket - node graph` then Prometheus is not involved in this process. k8spacket daemonset provides data as a JSON and Grafana gets it directly through the Grafana plugin (https://grafana.com/grafana/plugins/hamedkarbasi93-nodegraphapi-datasource/). Anyway, it is a great hint to add a possibility to get a node graph from the last, f.e., 1 hour only 👍 .

2. If the problem is connected with dashboard `k8spacket - metrics` where Prometheus serves saved metrics then it's a good point. The cardinality of these metrics can increase rapidly and scrapping by Prometheus can be harder. It's not easy to remove those metrics from endpoint `/metrics`, because k8spacket doesn't have clear information about deletion. Anyway, there should be a possibility to disable exposing those metrics 👍 . As a fast workaround, you can disable scrapping the k8spacket `/metrics` endpoint by Prometheus. Those metrics are not important for two main `k8spacket` dashboards:

- `k8spacket - node graph`
- `k8spacket - TLS connections & certificates`

I look forward to hearing from you if I understand the problem correctly.

**Comment by gevorgkhachatryan** [comment] 2024-03-04 09:20
Hi, thank you for your response.

I have a concern regarding pods in our Kubernetes cluster that have been deleted but still appear in the connection graph on the dashboard. Specifically, I observed that pods, that no longer exist (have been deleted), continue to be represented in Prometheus metrics as if they were still operational. These metrics remain static; for instance, a pod that had a metric value of 80 at the time of deletion continues to show this value in Prometheus even after its deletion. This issue leads to inaccuracies in the node graph, where, for example, it appears as though four pods are connected to a single pod, when in reality, only two exist—the other two were deleted four days ago.

Addressing this issue to ensure that deleted pods no longer send metrics(exporter I mean) to Prometheus would not only free up significant storage space but also ensure the node graph reflects the current, accurate state of the cluster. Your assistance in correcting this would be greatly appreciated.

**Comment by gevorgkhachatryan** [comment] 2024-03-04 09:21
by saying pods I mean application pods. And the problem I guess comes from the exporter. It should send metrics to Prometheus for deleted application pods

**Comment by k8spacket** [comment] 2024-03-04 13:04
Hi @gevorgkhachatryan 
Let's divide this problem into two points:

---

1. deleted pods on node graph dashboard (this one with circles)
<img width="1613" alt="image" src="https://github.com/k8spacket/k8spacket/assets/95187481/db3a3904-b0ba-4a45-b963-df537b2f4dc4">

- Would be solved with a feature where the node graph dashboard is sensitive to time range control. This is a great idea and I will analyze and add this option. 
- As I mentioned in the first comment, Prometheus is not involved in this process.

---

2. deleted pods in Prometheus metrics 
<img width="704" alt="image" src="https://github.com/k8spacket/k8spacket/assets/95187481/52d9adbb-8137-412e-9299-82e5444beb4d">

- Prometheus doesn't work in the way you described. Prometheus doesn't wait for metrics. Prometheus scrape metrics from targets in defined jobs: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config. To scrape metrics from k8spacket you have to add this kind of job to the Prometheus configuration:
```
    - job_name: "k8spacket-metrics"
      metrics_path: /metrics
      scrape_interval: 25s
      static_configs:
      - targets: [k8spacket.k8spacket.svc.cluster.local:8080]
```
k8spacket exposes metrics on the `/metrics` endpoint. If you didn't add it, then Prometheus knows nothing about k8spacket
- metrics in k8spacket work in this way
  - k8spacket sniffs connection between pod `A` and pod `B`
  - k8spacket exposes this metrics on endpoint `/metrics`, f.e.   ```k8s_packet_bytes_received_sum{dst="10.0.248.184",dst_name="B",dst_port="8081",ns="monitoring",persistent="false",src="10.2.17.98",src_name="A",src_port="dynamic"} 266220```
  - let's imagine now we delete pod `A`
  - k8spacket doesn't know about it (or knowing about it would be hard to maintain)
  - k8spacket still exposes metrics about pods A and B
  - Prometheus scrape these metrics in `scrape_interval` periods and that's why you still see these values

**Comment by gevorgkhachatryan** [comment] 2024-03-05 11:30
Hello,
Thank you for your prompt reply. I fully agree with the points you've raised and acknowledge the validity of your perspective. Indeed, you are correct. To provide some context, my primary expertise lies in monitoring, with a significant amount of experience specifically in Prometheus. I appreciate your explanations.

Concerning the first point you mentioned, I strongly encourage prioritizing it due to its importance. As for the issues we discussed:

k8spacket continues to report metrics for pods A and B.
Prometheus collects these metrics at regular scrape_interval periods, which explains the persistent data.
I'd like to propose a solution aimed at the exporter. It would be prudent to adjust it so that metrics from deleted pods are no longer reported. This suggestion stems from my initial concern and I believe it would effectively address the issue.

Thank you for considering my suggestion.

**Comment by gevorgkhachatryan** [comment] 2024-03-06 14:32
Hello, 
Thank you very much for your quick response. I will check and will go back to you.

**Comment by k8spacket** [comment] 2024-03-18 09:23
Hi @gevorgkhachatryan
I'm going to close this issue.

Thanks for your suggestions and input.
If you have more questions feel free to reopen it.

**Closed by k8spacket** 2024-03-18 09:23 UTC

**Comment by gevorgkhachatryan** [comment] 2024-03-18 11:12
Thanks a lot
